version: '3.1'
services:
  postgres:
    image: postgres:15
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: defaultdb
    ports:
      - "5432:5432"
    volumes:
      - ././volumes/postgres_data:/var/lib/postgresql/data




